alias ls="eza --color=always --long --git --no-filesize --icons=always --no-time --no-user --no-permissions --group-directories-first"
alias ll="eza --color=always --long --git --icons=always"
alias la="ls -a"
alias tree="ls --tree"

alias g="git"
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias gr="git remote"
alias gs="git status"
