theme = "tokyonight"

[editor]
line-number = "relative"
cursorline = true
true-color = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "underline"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1

[editor.whitespace]
render = "all"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "warning"
prefix-len = 10
max-diagnostics = 2

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]
